### ISSUE TITLE
[feat] CI/CD 구축

### ISSUE THREAD

**Issue by cha2y0ung** [TEAM-ITERVIEW/SERVER#3]
**Feature Request**
기능 설명 : 배포 자동화

**To-Do List**
- [x] RDS 생성
- [x] EC2 생성
- [x] develop 브랜치 생성
- [x] deploy.yml 파일 작성
- [x] S3 버킷 생성
- [x] AWS CodeDeploy 설정
