### ISSUE TITLE
[feat] 중간발표

### ISSUE THREAD

**Issue by cha2y0ung** [TEAM-ITERVIEW/SERVER#54]
**Feature Request**
기능 설명 : 기능 수정

**To-Do List**
- [x] interview title 숫자 1부터시작
- [x] interview title 날짜까지만. 뒤에 시간 떼기
- [x] delete 기능 interview/ router 쪽으로 옮기기
- [x] 문제 1개도 할수있게
- [x] gpt
